std_msgs/Header header
float64 x   # x position [mm]
float64 y   # y position [mm]
float64 z   # z position [mm]
float64 rvec_x  # x component of rotation vector [rad, axis-angle]
float64 rvec_y  # y component of rotation vector [rad, axis-angle]
float64 rvec_z  # z component of rotation vector [rad, axis-angle]
float64 x_vel  # x velocity [mm/s]
float64 y_vel  # y velocity [mm/s]
float64 z_vel  # z velocity [mm/s]
bool fire    # true if we have locked on to a target and will fire